services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ytdlp:
    build:
      context: ./docker/ytdlp
      dockerfile: Dockerfile
    container_name: ytdlp
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ytdlp_downloads:/downloads
      - ytdlp_cache:/root/.cache

  labse:
    build:
      context: ./docker/labse
      dockerfile: Dockerfile
    container_name: labse
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - labse_cache:/root/.cache

  whisper:
    build:
      context: ./docker/whisper
      dockerfile: Dockerfile
    container_name: whisper
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - whisper_cache:/root/.cache
      - whisper_models:/root/.cache/whisper

  n8n:
    build:
      context: ./docker/n8n
      dockerfile: Dockerfile
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - NODE_ENV=production
      - EXECUTIONS_DATA_PRUNE=true
      - NODE_FUNCTION_ALLOW_BUILTIN=fs,path,crypto
      - NODE_FUNCTION_ALLOW_EXTERNAL=openai
      - DB_SQLITE_POOL_SIZE=3
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - n8n_data:/home/node/.n8n
      - ytdlp_downloads:/downloads:ro
    depends_on:
      - elasticsearch
      - ollama

volumes:
  esdata:
  n8n_data:
  ollama_data:
  labse_cache:
  ytdlp_downloads:
  ytdlp_cache:
  whisper_cache:
  whisper_models:
